services:
  - type: web
    name: news-summary-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: uvicorn summarize_conclusion:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        value: 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