services:
  - type: web
    name: ai-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn summarize_conclusion_csv:app --reload
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Render의 Secret에 따로 등록
    autoDeploy: true
