services:
  - type: web
    name: news-summary-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: uvicorn summarize_conclusion_csv:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false